### ISSUE TITLE
[Bug] PF2E Compatibility

### ISSUE THREAD

**Issue by ChasarooniZ** [foundryvtt/unfulfilled-rolls#10]
Currently displays all roll results in PF2E as NAN vs the DC even when using default foundry dice rolls

**Comment by dogstarrb** [comment]
Also does not call for manual rolls when using attack/dmg etc buttons from the character sheet.

**Comment by myzar472** [comment]
A sample roll does appear to work. However, it impacts all rolls.

This is what it looks like in PF2e. This will occur whenever the module is enabled.

![image](https://github.com/foundryvtt/unfulfilled-rolls/assets/9061508/a2dc7de8-f8d7-4ed5-9b34-664e5a18150f)

**Comment by Simolsen** [comment]
i'm not getting asked to manual roll then using pf2e skills and attacks like anything in the sheet but then i use chat command to roll it works
