### ISSUE TITLE
Dice pool rolls do not open window for even sets of dice.

### ISSUE THREAD

**Issue by Irvanya** [foundryvtt/unfulfilled-rolls#17]
In  dice pool roll such as /r {2d20x, 2d6x, 2d6x, 2d20x}kh the window to show/enter dice does not open for the even sets of dice.  This prevents manual entry of dice.

It does correctly blink the dice and consume the roll results for bluetooth connected dice though.  So for the listed roll command it opens the prompt window for 2d20, blinks the dice, and consumes the roll result, then it blinks 2d6 without the prompt window, and consumes the results, 3rd it opens a prompt window again and blinks 2d6, consumes the results, and finally blinks 2d20 without opening the prompt window and consumes the results and processes the results to chat.  

As noted in another bug report any exploded dice use the digital roll instead of requesting another physical die roll and only explode once as if the xo option was used.

**Comment by MaxPat931** [comment]
Using the Manual Resolver, I cant get any dice group after the first to show the prompt even with just a simple `/r {1d10, 1d10}`, and the chat message doesnt resolve

https://github.com/foundryvtt/unfulfilled-rolls/assets/86370342/89d9c8b6-ab54-4b22-9fa3-af04b0214665

**Comment by MaxPat931** [comment]
The pools look to be fixed in latest update (only tested with manual roller, xplode dice are still handled by the system)
![image](https://github.com/foundryvtt/unfulfilled-rolls/assets/86370342/5d51c98b-7510-4a39-a6c0-9b66d15e3f24)

**Comment by Irvanya** [comment]
I also tested with the manual roller and confirm that everything appears to be working as expected.  Will confirm with bluetooth dice later today.  As noted above exploding dice are still handled by the system, but can explode more than once.  Closing the issue as resolved.
