### ISSUE TITLE
Dice Configuration - Foundry VTT Digital Roll fails

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/unfulfilled-rolls#18]
Foundry v11.302, Dnd5e 2.2.1, UR 0.1.0
Dice rolling fails when using Foundry VTT Digital Roll option
Send item to chat, click Attack, click Normal, error in console

![image](https://github.com/foundryvtt/unfulfilled-rolls/assets/86370342/45eda2ba-12cf-426e-b7f6-ee8689db5fbd)

**Comment by myzar472** [comment]
I do not believe I was able to replicate in D&D 5E, but this issue did occur on 0.1.0 on PF2E.

**Comment by Kaode** [comment]
I can confirm that I have this issue in D&D 5E. 
![image](https://github.com/foundryvtt/unfulfilled-rolls/assets/40830200/1b104094-8bc9-44bb-a773-184fc020f331)

**Comment by MaxPat931** [comment]
Looks to be fixed in 0.1.1 (dnd5e 2.2.1, Foundry v11.304)
