### ISSUE TITLE
1W20+1W20+1W20

### ISSUE THREAD

**Issue by BunteDimensionen** [foundryvtt/unfulfilled-rolls#24]
Yes, exactly have the problem with DSA5. The developer of DSA5 and the people of GoDice see the problem with the module "Unfulfilled-rolls" which does not implement the dice test 1W20+1W20+1W20 correctly.

**Comment by AKparticula** [comment]
@aaclayton 
Seems like this was solved

**Comment by aaclayton** [comment]
Thanks for the confirmation!
