### ISSUE TITLE
System does not find the GoDice App

### ISSUE THREAD

**Issue by Hijah82** [foundryvtt/unfulfilled-rolls#25]
The System prompts some mistakes. The GoDice App was not find in FoundryVTT? FoundryVTT and Mobile Device with the App are in the same WLAN.
![Screenshot 2023-07-14 092606](https://github.com/foundryvtt/unfulfilled-rolls/assets/137417695/57600b86-afcb-4d22-96df-3dc1bffb6a6e)
![Screenshot (19)](https://github.com/foundryvtt/unfulfilled-rolls/assets/137417695/cf439d6e-0bd2-4490-abac-a54b3a74f116)

**Comment by AKparticula** [comment]
@aaclayton  
Related to the GoDice app and was opened on the GoDice module, you can close the issue.
