### ISSUE TITLE
[PF2e] Critical Damage Rolls and Spell Damage Rolls Not Prompting 

### ISSUE THREAD

**Issue by 117ksk** [foundryvtt/unfulfilled-rolls#28]
Any damage rolls for spell damage or critical hit damage are rolling automatic virtual rolls despite dice types set as manual rolls.

**Comment by eturino** [comment]
I've tested my PR #31 with critical hits, spell damage and others and it works fine now. /cc @aaclayton @117ksk

**Comment by 117ksk** [comment]
Can confirm this PR fixes all crit and spell damage issues in PF2e as per my original post. Thank you!
