### ISSUE TITLE
[dnd5e 2.4] Hit Die cannot roll

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/unfulfilled-rolls#34]
Trying to roll a hit die in the latest dnd5e throws an error

![image](https://github.com/foundryvtt/unfulfilled-rolls/assets/86370342/0529646b-2d2e-44e3-8e47-a67d7ee1e7c1)

**Comment by guldelox** [comment]
This issue is still occurring.
![image](https://github.com/foundryvtt/unfulfilled-rolls/assets/67302749/ca9ea1a6-e0dd-494a-a7f4-99ec9db5a549)
