### ISSUE TITLE
[dnd5e] (X)dY[damage] throws TypeError: list is not iterable error

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/unfulfilled-rolls#35]
Foundry v11.315, DnD 2.4.0, UR 0.1.3

Adding an active effect that has both the die number in parenthesis *and* a damage type in brackets prevents damge from being rolled, with a  TypeError: list is not iterable error in the console  
![image](https://github.com/foundryvtt/unfulfilled-rolls/assets/86370342/54281040-a669-45ea-ba87-37ec56c8ebba)

`(2)d6[fire]` does not work
`2d6[fire]` works fine
`(2)d6` works fine

This error was found by trying to create an Active Effect that adds a scaling bonus to mwak.damage that scales with the level the spell is cast at with `(@item.level)d6[fire]` in an active effect, but can be replicated by adding the requisite formula in the Damage Formulas  
![image](https://github.com/foundryvtt/unfulfilled-rolls/assets/86370342/f30e0cf5-9853-418b-a60e-d653e2d5b07d)

**Comment by dineshm72** [comment]
I am having a similar issue using Rest Recovery 5e module.  Same error as above.  Not sure if it's same cause.

**Comment by dineshm72** [comment]
Fix from Michael:

The simple code change: in the scripts folder of the unfulfilled rolls module, pop open fulfillable-roll.mjs. Line 100 has : 
 if ( "dice" in term ) { 

change that if statement to:
 if (term.dice) {

Fixed by RR5e issue.  Might fix the above as well.
