### ISSUE TITLE
Module not installable with V12

### ISSUE THREAD

**Issue by Keyboard18** [foundryvtt/unfulfilled-rolls#39]
Trying to install the module results in:
Error: module unfulfilled-rolls version 0.1.2 requires an older version of the Foundry Virtual Tabletop software: 11 or older

**Comment by crlngn** [comment]
wondering if somebody got this working with v12. It is installable but I couldn't get it to see GoDice

**Comment by Keyboard18** [comment]
The option for GoDice is no longer visible in the "Unfulfilled Rolls" configuration. It has been moved to the "All" tab.

To access it:

    Open "Configuration Settings."
    Scroll down to the option "Configure Dice."
    Here, you'll find "GoDice Bluetooth Dice."

The only drawback now is that the dice do not indicate which one needs to be rolled. However, it still works.

**Comment by Keyboard18** [comment]
Somehow it's working now.

**Comment by crlngn** [comment]
> The option for GoDice is no longer visible in the "Unfulfilled Rolls" configuration. It has been moved to the "All" tab.
> 
> To access it:
 it. You really should update the docs
> ```
> Open "Configuration Settings."
> Scroll down to the option "Configure Dice."
> Here, you'll find "GoDice Bluetooth Dice."
> ```
> 
> The only drawback now is that the dice do not indicate which one needs to be rolled. However, it still works.

The "Configure Dice" option does not appear among the Settings buttons for me... I'm in v12. 
EDIT: Found it, docs were showing this somewhere else
